app = "carmetrics"
primary_region = "sin"

[build]
  [build.args]
    NEXT_PUBLIC_API_BASE = "https://carmetrics-api.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0