app = "carmetrics-api"
primary_region = "sin"

[build]

[env]
  DATABASE_PATH = "/data"

[mounts]
  source = "carmetrics_data"
  destination = "/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0